### PR TITLE
LPS-106188 fix the width of the indicator on the drop elements

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Hey @matuzalemsteles This is starting to looking good :)

Columns drag and drop I think works great, the thing we have to deal with yet is the container, the feedback about adding it inside we mentioned earlier,

I'm going to attach a video, because right now if you have a container in the root is impossible to add something to the root again, everything you drag it is added to the root. 

The other important issue is the feedback about the container, I think adding the column is not very feasible because it makes the structure strange, what do you think about having a threshold while dragging an item over a container like if it is near the border we count as the user want to add it in the container parent, and if it is in the middle of the container, we assume that the user wants to add the item inside. is this sound reasonable to you?

Anything you need to complete this task don't hesitate to ask us :)

Thanks a lot!

**Comment by matuzalemsteles** [comment]
hey @victorg1991 yeah, when the container is dragged by itself to the root element it will prevent the other elements from being added since it will add the nested elements, if we solve the case of the container we will solve that too.

> The other important issue is the feedback about the container, I think adding the column is not very feasible because it makes the structure strange, what do you think about having a threshold while dragging an item over a container like if it is near the border we count as the user want to add it in the container parent, and if it is in the middle of the container, we assume that the user wants to add the item inside. is this sound reasonable to you?

Yeah that might be a great idea, my concern is the interaction of the edges ... but maybe we can fix it. I will try it and get back with it again.

**Comment by victorg1991** [comment]
Nice @matuzalemsteles 

Thanks a lot!

**Comment by matuzalemsteles** [comment]
hey @victorg1991 I made the changes to allow the element to be added as sibling or nested depending on the region. When the element is in the middle it adds the nested element, I had to change the interaction to resemble that of the root element when we added an item for the first time, the feedback seems more natural. If we were to follow the old behavior, we would have to do some different interaction since in a container we can leave padding 0, so we had no way to give clear feedback to the user. Let me know what you think.

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/victorg1991/liferay-portal/pull/157. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Hey @matuzalemsteles I've rebased it here https://github.com/victorg1991/liferay-portal/pull/157 looking super good so far 😍

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83859. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/2a874c6ad630~3...2a874c6ad630) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83876. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/1f2d074fbde8~4...1f2d074fbde8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
