### PR TITLE
LPS-115454 The first checkbox is checked when click other label in Web Content Display confiuration dialog

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/1069. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
