### PR TITLE
LPS-107480

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Reviewing! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
this does not work on my machine

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83717. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
