### PR TITLE
LPS-104170 UI information on lock per experience

### PR DESCRIPTION
**Pull request by andresfulla**
Last 4 commits, please

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/474. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/1f42900235f6~1...1f42900235f6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
