### PR TITLE
LPS-93093 ContentSpace

### PR DESCRIPTION
**Pull request by petershin**
Hi @victorg1991, rerun the `buildREST` task to update the generated files.  If there are any issues, please modify one of the generated classes to the correct values and send the pull back to me.

### CODE REVIEW

**Comment by victorg1991** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
Hey @petershin thanks a lot :)

I'm waiting for the Javi PR https://github.com/brianchandotcom/liferay-portal/pull/70583 to be merged, which changes a lot of files

**Comment by brianchandotcom** [comment]
Guys, before i merge this in.. we really need to clear our debate over ContentSpace vs Group

Because if we go down this route, wouldn't it be easier if we just called it "groupId", and then merged in the Group object directly?

Right now, you can pass in any contentSpaceId which matches a groupId... I tend to agree with @marcoleo that we're overly complicating things. I think we should just go back to Group.

@jorgeferrer @marcoleo the 3 of us need to agree soon (i.e. in the next few days). I'm for calling it Group and groupId.

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70634. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/6237634be64b~4...6237634be64b)

**Pull request closed without merging**
