### PR TITLE
LPS-118302 Avoid refreshing when changing stylebook if possible

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/621. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/144ccb5eeec5~2...144ccb5eeec5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
