### PR TITLE
LPS-97633 Remove fragmentEntryLinks only when increasing number of columns

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75177. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/veroglez/liferay-portal/pull/33. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/ddde1be2fcc0~1...ddde1be2fcc0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
🤔

**Pull request closed without merging**
