### PR TITLE
LPS-96760 Don't display alert for Guest group since there is no name field in General tab

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/74554.

**Pull request closed without merging**
