### PR TITLE
LPS 99488

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @dacousalr,
I have tested your solution, it works well, thanks a lot!

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77913. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/bc4be4f79b00~1...bc4be4f79b00) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
