### PR TITLE
LPS-88164

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66078 thx.

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66105. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/7fa3b966b96f~1...7fa3b966b96f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66159. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/6b9fc7f06c7c~2...6b9fc7f06c7c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
