### PR TITLE
LPS-105467

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81724 and b994ad7d70cac76ec5b2ce707dc7c88dbc46a090

**Comment by victorg1991** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81744. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/3aa2e8a8c2d3~1...3aa2e8a8c2d3)

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81746. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/96b6607baac3~2...96b6607baac3)

**Pull request closed without merging**
