### PR TITLE
LPS-124594 As a Site Template Administrator, I want to have a one-click control for switching the propagation off and on

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by victorg1991** [comment]
Hey @moltam89 Can you send this pr to https://github.com/liferay-echo/liferay-portal better? 

Thanks!!

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/3729. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
