### PR TITLE
Bring back drag and drop the whole topper

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
🐼

**Comment by victorg1991** [comment]
ci:echo:test

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991, The acceptance case ContentPages#ReorganizeFragmentsInContentPage passed on my local. I think this PR is ready to merge.

**Pull request closed without merging**
