### PR TITLE
LPS-94626 Show an error message when moving pages without permission

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/sandrodw3/liferay-portal/pull/326. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/0f89755afb15~3...0f89755afb15) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
