### PR TITLE
LPS-98898

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76755

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76776. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/d4927b1375d2~1...d4927b1375d2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/2403. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
