### PR TITLE
LPS-119634 Adapt tests

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, when running the case, the inline content will be reset after typing. Additionally, the inline content is modified when access to page editor after case running. This issue can not reproduced manually.

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/tim-cao/liferay-portal/pull/401. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/d25cba349a91~5...d25cba349a91) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
