### PR TITLE
LPS-112618 Build lang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:rest:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/784. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/147798b0d790~1...147798b0d790) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/liferay-echo/liferay-portal/pull/483. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/147798b0d790~1...147798b0d790) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/tim-cao/liferay-portal/pull/256. [See changes here.](https://github.com/victorg1991/liferay-portal/compare/3829824cd53e~1...3829824cd53e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
