### PR TITLE
LPS-96822 Prevent unsused variables error in React

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@victorg1991 si quisieses ver los cambios en portal: https://github.com/p2kmgcl/liferay-portal/pull/393#issuecomment-510007029.

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/75537. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75539. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
